/**
 * Multilingual keywords for home-front / population-behavior relevance.
 * Used by social-media gather queries and pre-filtering citizen-voice content.
 */
export const HOMEFRONT_KEYWORDS = [
  'פיקוד העורף',
  'אזעקות',
  'אזעקה',
  'ממ"ד',
  'מרחב מוגן',
  'פינוי',
  'מפנה',
  'הנחיות העורף',
  'חירום',
  'מחסה',
  'התגוננות',
  'חזרה לבתי ספר',
  'בתי הספר',
  'לימודים',
  'תושבים',
  'אוכלוסייה',
  'התנהגות',
  'הנחיות',
  'אזור עורף',
  'עורף',
  'הכרעה',
  'המליץ',
  'שיגורים',
  'ירי מלבנון',
  'מספר האזעקות',
  'אזורים',
  'להתקלח',
  'לקניות',
  'חשש מאזעקה',
  'תבנית',
  'סדר',
  'מעקב',
  'נתונים',
  'יישוב',
  'בקעה',
  'ערבה',
  'עוטף עזה',
  'למידה מרחוק',
  'הכנות',
  'פתיחת בתי הספר',
  'מד"א',
  'חילוץ',
  'פינוי נפגעים',
  'שאיפת עשן',
  'שריפה',
  'איסור להיכנס',
  'אפיקי נחלים',
  'שיטפונות',
  'מזג אוויר',
  'הפרעות באספקת החשמל',
  'מצב נפשי',
  'נפשי',
  'רגשי',
  'חרדה',
  'חרדות',
  'טראומה',
  'פוסט טראומה',
  'פוסט-טראומה',
  'לחץ נפשי',
  'מתח',
  'פחד',
  'פחדים',
  'תמיכה נפשית',
  'תמיכה רגשית',
  'שירותים נפשיים',
  'חוסן נפשי',
  'חוסן',
  'התמודדות',
  'טיפול נפשי',
  'פסיכולוג',
  'עובד סוציאלי',
  'מצוקה נפשית',
  'משבר נפשי',
  'סיוע נפשי',
  'ערוך נפשית',
  'לחץ',
  'דחק',
  'אזעקות מחזירות',
  'שדה הקרב',
  'לא יוצא מהמיטה',
  'PTSD',
  'אוכלוסיות פגיעות',
  'אוכלוסיות מיוחדות',
  'אוכלוסייה מוחלשת',
  'קשישים',
  'גיל שלישי',
  'קשיש',
  'ילדים',
  'נוער',
  'תינוקות',
  'נשים בהריון',
  'בעלי מוגבלויות',
  'מוגבלות',
  'נכים',
  'עולים',
  'עולים חדשים',
  'אוכלוסייה בסיכון',
  'צרכים מיוחדים',
  'אנשים עם צרכים מיוחדים',
  'דיור מוגן',
  'בית אבות',
  'מעון',
  'פריפריה',
  'קהילה',
];

export const HOMEFRONT_KEYWORDS_ARA = [
  'قيادة الجبهة الداخلية', 'الجبهة الداخلية', 'جبهة الداخل',
  'صفارات الإنذار', 'صافرة الإنذار', 'إنذار جوي', 'إنذار',
  'ملجأ', 'غرفة آمنة', 'ملاجئ', 'مامد',
  'إخلاء', 'إجلاء', 'مهجرون', 'نازحون',
  'طوارئ', 'حالة طوارئ',
  'صواريخ', 'قذائف', 'قصف',
  'سكان', 'مقيمون', 'مدنيون',
  'مدارس', 'طلاب', 'تعليم',
  'شمال إسرائيل', 'الجليل', 'مستوطنات',
  'خوف', 'قلق', 'توتر', 'ضغط نفسي',
  'صدمة', 'صدمة نفسية', 'اضطراب ما بعد الصدمة',
  'دعم نفسي', 'صحة نفسية', 'صمود',
  'مسنون', 'أطفال', 'ذوو الاحتياجات الخاصة', 'نساء حوامل',
  'مجتمع', 'قرية', 'بلدة',
];

export const HOMEFRONT_KEYWORDS_RUS = [
  'Командование тылом', 'командование тыла', 'Пикуд а-Орев', 'тыл',
  'сирены', 'сирена', 'воздушная тревога', 'тревога',
  'убежище', 'безопасная комната', 'мамад', 'укрытие',
  'эвакуация', 'эвакуированные', 'переселенцы',
  'чрезвычайная ситуация', 'режим ЧС',
  'ракеты', 'обстрел', 'ракетный обстрел',
  'жители', 'население', 'мирные жители',
  'школы', 'дети', 'учащиеся', 'дистанционное обучение',
  'север Израиля', 'Галилея', 'поселения',
  'страх', 'тревожность', 'стресс', 'психологическое давление',
  'травма', 'ПТСР', 'посттравматическое', 'психологическая помощь',
  'психолог', 'психическое здоровье', 'устойчивость',
  'пожилые', 'дети', 'инвалиды', 'беременные',
  'репатрианты', 'новые репатрианты', 'олим',
  'сообщество', 'община',
];

export const HOMEFRONT_KEYWORDS_ENG = [
  'Home Front Command', 'civil defense', 'home front',
  'sirens', 'siren', 'air raid', 'alert', 'alarm',
  'bomb shelter', 'safe room', 'shelter',
  'evacuation', 'evacuees', 'displaced residents',
  'emergency', 'emergency situation',
  'rocket fire', 'rocket attack', 'missiles', 'shelling',
  'residents', 'civilians', 'population',
  'schools', 'students', 'remote learning', 'distance learning',
  'northern Israel', 'Galilee', 'communities',
  'anxiety', 'fear', 'stress', 'psychological',
  'trauma', 'PTSD', 'post-traumatic',
  'mental health', 'resilience', 'coping',
  'psychologist', 'counseling', 'emotional support',
  'elderly', 'children', 'disabled', 'pregnant',
  'immigrants', 'new immigrants', 'special needs',
  'community', 'settlement', 'town',
];

export const HOMEFRONT_KEYWORDS_FRA = [
  'commandement du front intérieur', 'défense civile', 'front intérieur',
  'sirènes', 'sirène', 'alerte', 'alerte aérienne',
  'abri', 'salle sécurisée', 'abris',
  'évacuation', 'évacués', 'déplacés',
  'urgence', 'situation d\'urgence',
  'tirs de roquettes', 'roquettes', 'missiles', 'bombardement',
  'résidents', 'civils', 'population',
  'écoles', 'élèves', 'enseignement à distance',
  'nord d\'Israël', 'Galilée', 'communautés',
  'anxiété', 'peur', 'stress', 'psychologique',
  'traumatisme', 'PTSD', 'post-traumatique',
  'santé mentale', 'résilience', 'faire face',
  'psychologue', 'soutien émotionnel',
  'personnes âgées', 'enfants', 'handicapés', 'femmes enceintes',
  'immigrants', 'nouveaux immigrants', 'besoins spéciaux',
  'communauté', 'ville',
];

const ALL_KEYWORD_SETS = [
  HOMEFRONT_KEYWORDS,
  HOMEFRONT_KEYWORDS_ARA,
  HOMEFRONT_KEYWORDS_RUS,
  HOMEFRONT_KEYWORDS_ENG,
  HOMEFRONT_KEYWORDS_FRA,
];

/**
 * @param {string} title
 * @param {string} body
 * @returns {boolean}
 */
export function isHomefrontRelevant(title, body) {
  const text = `${title || ''} ${body || ''}`;
  return ALL_KEYWORD_SETS.some((set) => set.some((kw) => text.includes(kw)));
}
