/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index', title: 'Getting Started' },
      items: [
        { type: 'doc', id: 'getting-started/using-the-app' },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'generated-index', title: 'Concepts' },
      items: [
        { type: 'doc', id: 'concepts/system-dataflow' },
        { type: 'doc', id: 'concepts/resilience-model' },
        { type: 'doc', id: 'concepts/signal-taxonomy' },
        { type: 'doc', id: 'concepts/scoring-model' },
        { type: 'doc', id: 'concepts/auth-model' },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'generated-index', title: 'Guides' },
      items: [
        { type: 'doc', id: 'guides/news-ingestion' },
        { type: 'doc', id: 'guides/whatsapp-integration' },
        { type: 'doc', id: 'guides/audio-ingestion' },
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'generated-index', title: 'Architecture' },
      items: [
        { type: 'doc', id: 'architecture/system-overview' },
        { type: 'doc', id: 'architecture/module-map' },
        { type: 'doc', id: 'architecture/storage' },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        { type: 'doc', id: 'api/index' },
        { type: 'autogenerated', dirName: 'api/generated' },
      ],
    },
  ],
};

module.exports = sidebars;

