/**
 * Loads and parses articles-*.md files generated by fetch-articles-to-md.js.
 * Produces a flat array of article objects for LLM analysis.
 */

import { readFileSync } from 'node:fs';
import { basename } from 'node:path';
import {
  parseSectionMeta,
  splitNumberedSections,
} from '../../../cross-cut-modules/markdown/markdownArticleSections.js';

const MAX_BODY_CHARS = 2000;
const MD_HEADER_RE = /^#\s+(.+?)\s+articles\s+\((\d{4}-\d{2}-\d{2})\)/m;
const HOMEFRONT_URL_RE = /\*\*URL:\*\*\s*(https?:\/\/\S+)/;

function parseMdFile(content, sourcePath) {
  const headerMatch = MD_HEADER_RE.exec(content);
  const siteName = headerMatch?.[1] ?? basename(sourcePath, '.md');
  const date = headerMatch?.[2] ?? null;

  const sections = splitNumberedSections(content);
  const articles = [];

  for (const section of sections) {
    const meta = parseSectionMeta(section, { urlRe: HOMEFRONT_URL_RE });
    if (!meta) continue;

    articles.push({
      title: meta.title,
      url: meta.url,
      publishedAt: meta.publishedAt,
      source: meta.source || siteName,
      body: meta.body.slice(0, MAX_BODY_CHARS),
      sourceFile: basename(sourcePath),
    });
  }

  return { siteName, date, articles };
}

export function loadMdFile(filePath) {
  const content = readFileSync(filePath, 'utf-8');
  return parseMdFile(content, filePath);
}

const TEMPORAL_WEIGHTS = { 0: 1, 1: 0.85, 2: 0.7 };

/**
 * Load multiple MD files and merge all articles into one array.
 * @param {string[]} filePaths
 * @param {{ dayOffsets?: number[] }} [opts]  dayOffsets[i] = days before today for filePaths[i] (0=today, 1=yesterday, 2=day-before)
 * Returns { articles, date, totalCount, siteNames }.
 */
export function loadMdFiles(filePaths, { dayOffsets = [] } = {}) {
  const allArticles = [];
  const dates = new Set();
  const siteNames = [];

  for (let i = 0; i < filePaths.length; i++) {
    const fp = filePaths[i];
    const dayOffset = dayOffsets[i] ?? 0;
    const temporalWeight = TEMPORAL_WEIGHTS[dayOffset] ?? 1;
    const { siteName, date, articles } = loadMdFile(fp);
    if (date) dates.add(date);
    siteNames.push(siteName);
    for (const a of articles) {
      allArticles.push({ ...a, temporal_weight: temporalWeight });
    }
  }

  return {
    articles: allArticles,
    date: [...dates][0] ?? 'Unknown',
    totalCount: allArticles.length,
    siteNames,
  };
}
