/**
 * Loads and parses articles-*.md files generated by fetch-articles-to-md.js.
 * Produces a flat array of article objects for LLM analysis.
 */

import { readFileSync } from 'fs';
import { basename } from 'path';

const MAX_BODY_CHARS = 2000; // Truncate bodies to keep token budget manageable

/**
 * Parse one markdown file into structured articles.
 * Expected format:
 *   # Site articles (YYYY-MM-DD)
 *   Total: N articles
 *   ## 1. Title
 *   - **URL:** ...
 *   - **Published:** ...
 *   - **Source:** ...
 *   <body>
 *   ---
 */
function parseMdFile(content, sourcePath) {
  const headerMatch = content.match(/^#\s+(.+?)\s+articles\s+\((\d{4}-\d{2}-\d{2})\)/m);
  const siteName = headerMatch?.[1] ?? basename(sourcePath, '.md');
  const date = headerMatch?.[2] ?? null;

  // Split on numbered article headers
  const sections = content.split(/\n(?=## \d+\. )/);
  const articles = [];

  for (const section of sections) {
    const titleMatch = section.match(/^## \d+\.\s+(.+)/m);
    if (!titleMatch) continue;

    const title = titleMatch[1].trim();
    const urlMatch = section.match(/\*\*URL:\*\*\s*(https?:\/\/\S+)/);
    const publishedMatch = section.match(/\*\*Published:\*\*\s*([^\n]+)/);
    const sourceMatch = section.match(/\*\*Source:\*\*\s*([^\n]+)/);

    // Body: everything after the last metadata line, before the trailing ---
    const metaEnd = section.lastIndexOf('\n- **');
    const afterMeta = metaEnd >= 0 ? section.slice(metaEnd) : section;
    const bodyStart = afterMeta.indexOf('\n\n');
    let body = bodyStart >= 0 ? afterMeta.slice(bodyStart).trim() : '';
    body = body.replace(/\n---\s*$/, '').trim();

    articles.push({
      title,
      url: urlMatch?.[1]?.trim() ?? '',
      publishedAt: publishedMatch?.[1]?.trim() ?? '',
      source: sourceMatch?.[1]?.trim() ?? siteName,
      body: body.slice(0, MAX_BODY_CHARS),
      sourceFile: basename(sourcePath),
    });
  }

  return { siteName, date, articles };
}

export function loadMdFile(filePath) {
  const content = readFileSync(filePath, 'utf-8');
  return parseMdFile(content, filePath);
}

const TEMPORAL_WEIGHTS = { 0: 1.00, 1: 0.85, 2: 0.70 };

/**
 * Load multiple MD files and merge all articles into one array.
 * @param {string[]} filePaths
 * @param {{ dayOffsets?: number[] }} [opts]  dayOffsets[i] = days before today for filePaths[i] (0=today, 1=yesterday, 2=day-before)
 * Returns { articles, date, totalCount, siteNames }.
 */
export function loadMdFiles(filePaths, { dayOffsets = [] } = {}) {
  const allArticles = [];
  const dates = new Set();
  const siteNames = [];

  for (let i = 0; i < filePaths.length; i++) {
    const fp = filePaths[i];
    const dayOffset = dayOffsets[i] ?? 0;
    const temporalWeight = TEMPORAL_WEIGHTS[dayOffset] ?? 1.00;
    const { siteName, date, articles } = loadMdFile(fp);
    if (date) dates.add(date);
    siteNames.push(siteName);
    for (const a of articles) {
      allArticles.push({ ...a, temporal_weight: temporalWeight });
    }
  }

  return {
    articles: allArticles,
    date: [...dates][0] ?? 'Unknown',
    totalCount: allArticles.length,
    siteNames,
  };
}
