/**
 * Mailing digest copy and label constants (en / he / ru).
 */

export const LABELS = {
  en: {
    reportTitle: '8 components — daily resilience report',
    naftaliTitle: 'Pools — Naftali',
    educationTitle: 'Pools — Education',
    platformTitle: 'Platform notices',
    noReport: 'No report available for this run.',
    noSummary: 'No executive summary.',
    score: 'score',
    metadata: 'Metadata',
    reportDate: 'Report date',
    generatedAt: 'Generated at',
    totalArticles: 'Articles analyzed',
    pboReports: 'PBO reports',
    dataByDay: 'Data included by day',
    date: 'Date',
    articles: 'Articles',
    overallScore: 'Overall score',
    instrumentSummary: 'Evidence summary',
    confidence: 'confidence',
    components: 'Components',
    executiveSummary: 'Executive summary',
    componentNarratives: 'Component narratives',
    subject: 'Vibes Witch — digest',
    openInApp: 'Open in Vibeswitch',
    viewDetails: 'View details',
  },
  he: {
    reportTitle: '8 מרכיבים — דוח חוסן יומי',
    naftaliTitle: 'בריכות — נפתלי',
    educationTitle: 'בריכות — חינוך',
    platformTitle: 'הודעות מערכת',
    noReport: 'אין דוח זמין להרצה זו.',
    noSummary: 'אין סיכום מנהלים.',
    score: 'ציון',
    metadata: 'מטא־דאטה',
    reportDate: 'תאריך הדוח',
    generatedAt: 'נוצר בתאריך',
    totalArticles: 'כתבות שנותחו',
    pboReports: 'דוחות קב"ט',
    dataByDay: 'נתונים שנכללו לפי יום',
    date: 'תאריך',
    articles: 'כתבות',
    overallScore: 'ציון כולל',
    instrumentSummary: 'סיכום ראיות',
    confidence: 'רמת ביטחון',
    components: 'מרכיבים',
    executiveSummary: 'סיכום מנהלים',
    componentNarratives: 'נרטיבים לפי מרכיב',
    subject: 'Vibes Witch — דיוור יומי',
    openInApp: 'פתיחה ב־Vibeswitch',
    viewDetails: 'לפרטים באתר',
  },
  ru: {
    reportTitle: '8 компонентов — ежедневный отчёт устойчивости',
    naftaliTitle: 'Пулы — Нафтали',
    educationTitle: 'Пулы — Образование',
    platformTitle: 'Сообщения системы',
    noReport: 'Отчёт недоступен для этой отправки.',
    noSummary: 'Нет краткого резюме.',
    score: 'оценка',
    metadata: 'Метаданные',
    reportDate: 'Дата отчёта',
    generatedAt: 'Создано',
    totalArticles: 'Статей проанализировано',
    pboReports: 'Отчёты ПБО',
    dataByDay: 'Данные по дням',
    date: 'Дата',
    articles: 'Статьи',
    overallScore: 'Общая оценка',
    instrumentSummary: 'Сводка по доказательствам',
    confidence: 'уверенность',
    components: 'Компоненты',
    executiveSummary: 'Краткое резюме',
    componentNarratives: 'Текстовые выводы по компонентам',
    subject: 'Vibes Witch — дайджест',
    openInApp: 'Открыть в Vibeswitch',
    viewDetails: 'Подробнее на сайте',
  },
};

export const DEFAULT_APP_BASE_URL = 'https://srulik.ai';

export const COMPONENT_LABELS = {
  en: {
    narrative: 'Narrative',
    information_communication: 'Information and communication',
    lifesaving_behavior: 'Lifesaving behavior',
    functional_continuity: 'Functional continuity',
    community_capital: 'Community capital',
    leadership: 'Leadership',
    belonging_solidarity: 'Belonging and solidarity',
    wellbeing_at_risk: 'Wellbeing and at-risk groups',
  },
  he: {
    narrative: 'נרטיב',
    information_communication: 'מידע ותקשורת',
    lifesaving_behavior: 'התנהגות מצילת חיים',
    functional_continuity: 'רציפות תפקודית',
    community_capital: 'הון קהילתי',
    leadership: 'מנהיגות',
    belonging_solidarity: 'שייכות וסולידריות',
    wellbeing_at_risk: 'רווחה וקבוצות בסיכון',
  },
  ru: {
    narrative: 'Нарратив',
    information_communication: 'Информация и коммуникация',
    lifesaving_behavior: 'Поведение, спасающее жизнь',
    functional_continuity: 'Функциональная непрерывность',
    community_capital: 'Общественный капитал',
    leadership: 'Лидерство',
    belonging_solidarity: 'Принадлежность и солидарность',
    wellbeing_at_risk: 'Благополучие и группы риска',
  },
};

export const POOL_COLORS = {
  red: '#dc2626',
  amber: '#d97706',
  green: '#16a34a',
  blue: '#2563eb',
  purple: '#7c3aed',
  teal: '#0d9488',
  gray: '#64748b',
  grayLight: '#cbd5e1',
};

export const NAF_SEVERITY_KEYS = ['financialRequests', 'schoolMentalHealth', 'communityMentalHealth', 'parentalStress', 'coupleConflicts', 'parentChildConflicts'];
export const NAF_VULN_KEYS = ['physicalDisability', 'mentalDisability', 'specialEducation', 'domesticViolence', 'severeFinancial', 'singleParent'];
export const POOL_LABELS = {
  en: {
    totalResponses: 'Total responses',
    weeks: 'Weeks',
    municipalities: 'Municipalities',
    settlements: 'Settlements',
    latestSession: 'Latest session',
    dateRange: 'Date range',
    noData: 'No pool data available.',
    severityTrends: 'Severity trends over time',
    vulnerablePopulations: 'Vulnerable population counts',
    challengesNeeds: 'Challenges & needs',
    copingOverTime: 'Coping level over time',
    streetMovement: 'Street movement',
    informalContact: 'Informal contact with children',
    concerningTrends: 'Concerning trends',
    interventionNeeded: 'Intervention needed',
    openResponses: 'Open responses',
    municipality: 'Municipality',
    settlement: 'Settlement',
    challenge: 'Main challenge',
    urgentNeeds: 'Urgent needs',
    comment: 'Comment',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    none: 'None',
    indifferent: 'Indifferent',
    coping_easily: 'Coping easily',
    struggling_somewhat: 'Struggling somewhat',
    struggling_greatly: 'Struggling greatly',
    other: 'Other',
    rarely: 'Rarely',
    yes: 'Yes',
    no: 'No',
    maybe: 'Maybe',
    financialRequests: 'Financial hardship requests',
    schoolMentalHealth: 'School mental health',
    communityMentalHealth: 'Community mental health',
    parentalStress: 'Parental stress',
    coupleConflicts: 'Couple conflicts',
    parentChildConflicts: 'Parent-child conflicts',
    physicalDisability: 'Physical disability',
    mentalDisability: 'Mental disability',
    specialEducation: 'Special education',
    domesticViolence: 'Domestic violence',
    severeFinancial: 'Severe financial',
    singleParent: 'Single parent',
    drugs: 'Drugs',
    alcohol: 'Alcohol',
    physical_violence: 'Physical violence',
    verbal_violence: 'Verbal violence',
    screens: 'Screens',
    loneliness: 'Loneliness / isolation',
    none_observed: 'None observed',
  },
  he: {
    totalResponses: 'סך תגובות',
    weeks: 'שבועות',
    municipalities: 'יישובים',
    settlements: 'יישובים',
    latestSession: 'סשן אחרון',
    dateRange: 'טווח תאריכים',
    noData: 'אין נתוני בריכות זמינים.',
    severityTrends: 'מגמות חומרה לאורך זמן',
    vulnerablePopulations: 'ספירת אוכלוסיות פגיעות',
    challengesNeeds: 'אתגרים וצרכים',
    copingOverTime: 'רמת התמודדות לאורך זמן',
    streetMovement: 'תנועה ברחובות',
    informalContact: 'קשר לא-פורמלי עם ילדים',
    concerningTrends: 'מגמות מדאיגות',
    interventionNeeded: 'האם נדרשת התערבות',
    openResponses: 'תגובות פתוחות',
    municipality: 'יישוב',
    settlement: 'יישוב',
    challenge: 'אתגר מרכזי',
    urgentNeeds: 'צרכים דחופים',
    comment: 'תגובה',
    high: 'גבוה',
    medium: 'בינוני',
    low: 'נמוך',
    none: 'אין',
    indifferent: 'אדישים',
    coping_easily: 'מתמודדים בקלות',
    struggling_somewhat: 'קצת מתקשים',
    struggling_greatly: 'מתקשים מאוד',
    other: 'אחר',
    rarely: 'כמעט ולא',
    yes: 'כן',
    no: 'לא',
    maybe: 'אולי',
    financialRequests: 'בקשות מצוקה כלכלית',
    schoolMentalHealth: 'בריאות נפשית בבית הספר',
    communityMentalHealth: 'בריאות נפשית בקהילה',
    parentalStress: 'לחץ הורי',
    coupleConflicts: 'קונפליקטים זוגיים',
    parentChildConflicts: 'קונפליקטים הורה-ילד',
    physicalDisability: 'מוגבלות פיזית',
    mentalDisability: 'מוגבלות נפשית',
    specialEducation: 'חינוך מיוחד',
    domesticViolence: 'אלימות במשפחה',
    severeFinancial: 'מצוקה כלכלית חמורה',
    singleParent: 'הורה יחידני',
    drugs: 'סמים',
    alcohol: 'אלכוהול',
    physical_violence: 'אלימות פיזית',
    verbal_violence: 'אלימות מילולית',
    screens: 'מסכים',
    loneliness: 'בדידות / הימנעות',
    none_observed: 'לא נצפה',
  },
  ru: {
    totalResponses: 'Всего ответов',
    weeks: 'Недели',
    municipalities: 'Муниципалитеты',
    settlements: 'Населённые пункты',
    latestSession: 'Последняя сессия',
    dateRange: 'Период',
    noData: 'Данные пулов недоступны.',
    severityTrends: 'Динамика серьёзности',
    vulnerablePopulations: 'Уязвимые группы',
    challengesNeeds: 'Проблемы и потребности',
    copingOverTime: 'Уровень совладания во времени',
    streetMovement: 'Движение на улицах',
    informalContact: 'Неформальный контакт с детьми',
    concerningTrends: 'Тревожные тенденции',
    interventionNeeded: 'Нужна интервенция',
    openResponses: 'Открытые ответы',
    municipality: 'Муниципалитет',
    settlement: 'Населённый пункт',
    challenge: 'Главная проблема',
    urgentNeeds: 'Срочные потребности',
    comment: 'Комментарий',
    high: 'Высокий',
    medium: 'Средний',
    low: 'Низкий',
    none: 'Нет',
    indifferent: 'Безразличны',
    coping_easily: 'Справляются легко',
    struggling_somewhat: 'Есть трудности',
    struggling_greatly: 'Сильные трудности',
    other: 'Другое',
    rarely: 'Редко',
    yes: 'Да',
    no: 'Нет',
    maybe: 'Возможно',
    financialRequests: 'Запросы по финансовым трудностям',
    schoolMentalHealth: 'Психическое здоровье в школе',
    communityMentalHealth: 'Психическое здоровье в сообществе',
    parentalStress: 'Родительский стресс',
    coupleConflicts: 'Конфликты в парах',
    parentChildConflicts: 'Конфликты родитель-ребёнок',
    physicalDisability: 'Физическая инвалидность',
    mentalDisability: 'Психическая инвалидность',
    specialEducation: 'Специальное образование',
    domesticViolence: 'Домашнее насилие',
    severeFinancial: 'Тяжёлые финансовые трудности',
    singleParent: 'Одинокий родитель',
    drugs: 'Наркотики',
    alcohol: 'Алкоголь',
    physical_violence: 'Физическое насилие',
    verbal_violence: 'Вербальное насилие',
    screens: 'Экраны',
    loneliness: 'Одиночество / изоляция',
    none_observed: 'Не наблюдалось',
  },
};
